management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: /disqualified-officers-data-api/healthcheck
    health:
      show-details: never
      enabled: true

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}
      enabled: ${DSQ_STREAM_HOOK_ENABLED:true}

logger:
  namespace: disqualified-officer-data-api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://mongo:27017}/disqualifications?retryWrites=false
      name: disqualifications
  jackson:
    default-property-inclusion: NON_NULL

mongodb:
  disqualifications:
    collection:
      name: disqualifications