# Test-specific properties for integration and Cucumber tests
spring.data.mongodb.database=disqualified-officers-test
disqualified.officers.api.base-url=http://localhost:8080
spring.mongodb.uri=${MONGODB_URL}